version: "3"

services:
  db:
    container_name: go_anon_db
    # restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_anon
  # server:
  #   container_name: go_anon_server
  #   # restart: always
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     ENVIRONMENT: prod
  #   depends_on:
  #     - db
